"""Application settings dialog.

This module provides a Qt-based dialog for viewing, editing, saving, and
restoring application settings. It wraps the settings GUI generated by
Qt Designer and connects it to the underlying configuration backend.
"""

import logging

import PyQt6 as PyQt

from ramangui import settings_gui as SettingsGUI
from ramangui import utils

logger = logging.getLogger(__name__)


class SettingsApp(PyQt.QtWidgets.QDialog):
    """Dialog for displaying and managing application settings.

    This dialog allows the user to view, modify, save, and restore application
    settings stored in a configuration file.
    """

    def __init__(self, settings):
        """Initialize the settings dialog and load current settings.

        Parameters
        ----------
        settings : object
            Settings backend object providing get(), set(), and save() methods.
        """
        logger.debug("Initializing SettingsApp...")
        super().__init__()

        self.ui = SettingsGUI.Ui_Dialog_Settings()
        self.ui.setupUi(self)
        logger.debug("Settings UI setup completed.")

        self.ui.buttonBox.clicked.connect(self.buttonHandle)
        self.ui.buttonBox.accepted.connect(self.saveSettings)
        logger.debug("Settings dialog signals connected.")

        self.settings = settings
        self.loadSettings()
        logger.info("SettingsApp initialized and settings loaded into UI.")

    def buttonHandle(self, a):
        """Handle button clicks in the dialog.

        This method currently reacts to the *Restore Defaults* button and
        triggers a reset of the configuration.

        Parameters
        ----------
        a : QAbstractButton
            The button that was clicked.
        """
        logger.debug("Settings dialog button clicked: %s", a.text())
        if a.text() == "Restore Defaults":
            logger.info("Restoring default settings requested.")
            self.writeDefaultSettings()

    def loadSettings(self):
        """Load settings from the configuration backend into the UI.

        Reads values from the settings object and populates all corresponding
        UI fields.
        """
        settings = self.settings
        logger.debug("Loading settings into SettingsApp UI...")

        try:
            if settings.get("StrainType") == "uniaxial":
                self.ui.comboBox_StrainType.setCurrentIndex(0)
            elif settings.get("StrainType") == "biaxial":
                self.ui.comboBox_StrainType.setCurrentIndex(1)

            self.ui.comboBox_ScanDirection.setCurrentIndex(settings.get("ScanDirection"))

            self.ui.lineEdit_StrainSlope.setText(str(settings.get("Slope_Strain")))
            self.ui.lineEdit_DopingSlope.setText(str(settings.get("Slope_Doping")))

            self.ui.lineEdit_Gamma_G_0.setText(str(settings.get("Gamma_G_0")))
            self.ui.lineEdit_Gamma_2D_0.setText(str(settings.get("Gamma_2D_0")))
            self.ui.lineEdit_Gamma_D_0.setText(str(settings.get("Gamma_D_0")))
            self.ui.lineEdit_omega_G_0.setText(str(settings.get("omega_G_0")))
            self.ui.lineEdit_omega_2d_0.setText(str(settings.get("omega_2D_0")))
            self.ui.lineEdit_omega_D_0.setText(str(settings.get("omega_D_0")))
            self.ui.lineEdit_spec_width_G.setText(str(settings.get("spec_width_G")))
            self.ui.lineEdit_spec_width_2D.setText(str(settings.get("spec_width_2D")))
            self.ui.lineEdit_spec_width_D.setText(str(settings.get("spec_width_D")))
            self.ui.lineEdit_omega_2d_maxError.setText(str(settings.get("omega_2D_maxError")))
            self.ui.lineEdit_area_2D_min.setText(str(settings.get("area_2D_min")))
            self.ui.lineEdit_area_2D_max.setText(str(settings.get("area_2D_max")))
            self.ui.lineEdit_Gamma_G_min.setText(str(settings.get("Gamma_G_min")))
            self.ui.lineEdit_Gamma_G_max.setText(str(settings.get("Gamma_G_max")))
            self.ui.lineEdit_Gamma_2D_min.setText(str(settings.get("Gamma_2D_min")))
            self.ui.lineEdit_Gamma_2D_max.setText(str(settings.get("Gamma_2D_max")))
            self.ui.comboBox_Mask.setCurrentIndex(settings.get("UseFitMask"))
            self.ui.lineEdit_LaserWavelength.setText(str(settings.get("LaserWavelength")))
            self.ui.checkBox_4P_Mode.setChecked(bool(settings.get("4_P_mode")))
            self.ui.lineEdit_PeakPos_1.setText(str(settings.get("omega_peak_1")))
            self.ui.lineEdit_PeakPos_2.setText(str(settings.get("omega_peak_2")))
            self.ui.lineEdit_PeakPos_3.setText(str(settings.get("omega_peak_3")))
            self.ui.lineEdit_PeakPos_4.setText(str(settings.get("omega_peak_4")))
            self.ui.lineEdit_PeakWidth_1.setText(str(settings.get("Gamma_peak_1")))
            self.ui.lineEdit_PeakWidth_2.setText(str(settings.get("Gamma_peak_2")))
            self.ui.lineEdit_PeakWidth_3.setText(str(settings.get("Gamma_peak_3")))
            self.ui.lineEdit_PeakWidth_4.setText(str(settings.get("Gamma_peak_4")))

            logger.info("Settings loaded into UI.")
        except Exception:
            logger.exception("Failed to load settings into UI.")

    def saveSettings(self):
        """Save current UI values to the configuration backend.

        Converts UI input fields to numeric values and writes them to the
        settings object. Displays an error dialog if conversion fails.
        """
        settings = self.settings
        logger.info("Saving settings from UI...")

        try:
            strain_type_map = {0: "uniaxial", 1: "biaxial"}

            settings.set(
                "StrainType",
                strain_type_map.get(self.ui.comboBox_StrainType.currentIndex(), "uniaxial"),
            )
            settings.set("ScanDirection", int(self.ui.comboBox_ScanDirection.currentIndex()))

            settings.set("Slope_Strain", float(self.ui.lineEdit_StrainSlope.text()))
            settings.set("Slope_Doping", float(self.ui.lineEdit_DopingSlope.text()))

            settings.set("Gamma_G_0", float(self.ui.lineEdit_Gamma_G_0.text()))
            settings.set("Gamma_2D_0", float(self.ui.lineEdit_Gamma_2D_0.text()))
            settings.set("Gamma_D_0", float(self.ui.lineEdit_Gamma_D_0.text()))
            settings.set("omega_G_0", float(self.ui.lineEdit_omega_G_0.text()))
            settings.set("omega_2D_0", float(self.ui.lineEdit_omega_2d_0.text()))
            settings.set("omega_D_0", float(self.ui.lineEdit_omega_D_0.text()))
            settings.set("spec_width_G", float(self.ui.lineEdit_spec_width_G.text()))
            settings.set("spec_width_2D", float(self.ui.lineEdit_spec_width_2D.text()))
            settings.set("spec_width_D", float(self.ui.lineEdit_spec_width_D.text()))
            settings.set("omega_2D_maxError", float(self.ui.lineEdit_omega_2d_maxError.text()))
            settings.set("area_2D_min", float(self.ui.lineEdit_area_2D_min.text()))
            settings.set("area_2D_max", float(self.ui.lineEdit_area_2D_max.text()))
            settings.set("Gamma_G_min", float(self.ui.lineEdit_Gamma_G_min.text()))
            settings.set("Gamma_G_max", float(self.ui.lineEdit_Gamma_G_max.text()))
            settings.set("Gamma_2D_min", float(self.ui.lineEdit_Gamma_2D_min.text()))
            settings.set("Gamma_2D_max", float(self.ui.lineEdit_Gamma_2D_max.text()))
            settings.set("UseFitMask", int(self.ui.comboBox_Mask.currentIndex()))
            settings.set("LaserWavelength", float(self.ui.lineEdit_LaserWavelength.text()))
            settings.set("4_P_mode", int(self.ui.checkBox_4P_Mode.isChecked()))
            settings.set("omega_peak_1", float(self.ui.lineEdit_PeakPos_1.text()))
            settings.set("omega_peak_2", float(self.ui.lineEdit_PeakPos_2.text()))
            settings.set("omega_peak_3", float(self.ui.lineEdit_PeakPos_3.text()))
            settings.set("omega_peak_4", float(self.ui.lineEdit_PeakPos_4.text()))
            settings.set("Gamma_peak_1", float(self.ui.lineEdit_PeakWidth_1.text()))
            settings.set("Gamma_peak_2", float(self.ui.lineEdit_PeakWidth_2.text()))
            settings.set("Gamma_peak_3", float(self.ui.lineEdit_PeakWidth_3.text()))
            settings.set("Gamma_peak_4", float(self.ui.lineEdit_PeakWidth_4.text()))
            settings.save()

            msg = PyQt.QtWidgets.QMessageBox(self)
            msg.setIcon(PyQt.QtWidgets.QMessageBox.Information)
            msg.setWindowTitle("Settings Changed")
            msg.setText("A new fit is required.")
            msg.setInformativeText(
                "Some settings were modified. Please run the fit again for the changes to take effect."
            )
            msg.setStandardButtons(PyQt.QtWidgets.QMessageBox.Ok)
            msg.exec()

            logger.info("Settings saved successfully.")
        except Exception as exceptiontext:
            logger.warning("Settings could not be saved due to invalid input.", exc_info=True)
            msg = PyQt.QtWidgets.QMessageBox()
            msg.setIcon(PyQt.QtWidgets.QMessageBox.Critical)
            msg.setText("Settings could not be saved!")
            msg.setInformativeText(
                "An error occurred while converting your input to numbers! "
                "Only integer numbers and decimal numbers with point decimal separator are supported."
            )
            msg.setWindowTitle("Error")
            msg.setDetailedText(str(exceptiontext))
            msg.setStandardButtons(PyQt.QtWidgets.QMessageBox.Ok)
            msg.exec_()

    def writeDefaultSettings(self):
        """Restore default settings and reload them into the UI.

        Replaces the current settings with default values and updates all
        UI elements accordingly.
        """
        logger.info("Writing default settings and reloading UI.")
        try:
            self.settings = utils.restore_default_settings(self.settings)
            self.loadSettings()
            logger.info("Default settings restored.")
        except Exception:
            logger.exception("Failed to restore default settings.")
