# Configuration
StrainType=uniaxial
ScanDirection=I0(es_nl).
Gamma_G_0=I15(es_nl).
Gamma_2D_0=I25(es_nl).
Gamma_D_0=I10(es_nl).
omega_G_0=I1585(es_nl).
omega_2D_0=I2675(es_nl).
omega_D_0=I1350(es_nl).
spec_width_G=I120(es_nl).
spec_width_2D=I170(es_nl).
spec_width_D=I100(es_nl).
omega_2D_maxError=I3(es_nl).
area_2D_min=I50(es_nl).
area_2D_max=F10000000.0(es_nl).
Gamma_G_min=I3(es_nl).
Gamma_G_max=I70(es_nl).
Gamma_2D_min=I7(es_nl).
Gamma_2D_max=I110(es_nl).
UseFitMask=I1(es_nl).
LaserWavelength=I532(es_nl).
4_P_mode=I00(es_nl).
omega_peak_1=I2650(es_nl).
omega_peak_2=I2685(es_nl).
omega_peak_3=I2700(es_nl).
omega_peak_4=I2720(es_nl).
Gamma_peak_1=I20(es_nl).
Gamma_peak_2=I20(es_nl).
Gamma_peak_3=I20(es_nl).
Gamma_peak_4=I20(es_nl).
Slope_Strain=F2.2(es_nl).
Slope_Doping=F0.4(es_nl).
